<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUgByN0y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgByN0y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUgByN0y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUgByN0y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUgByN0y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UgByN0y',
    'container.build_id' => '8521fa57',
    'container.build_time' => 1649980713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgByN0y');
