<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'display_activite' => [[], ['_controller' => 'App\\Controller\\ActiviteController::index'], [], [['text', '/']], [], []],
    'display_admin' => [[], ['_controller' => 'App\\Controller\\ActiviteController::indexAdmin'], [], [['text', '/front']], [], []],
    'addActivite' => [[], ['_controller' => 'App\\Controller\\ActiviteController::addActivite'], [], [['text', '/addActivite']], [], []],
    'supp_activite' => [['id'], ['_controller' => 'App\\Controller\\ActiviteController::suppressionActivite'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/removeActivite']], [], []],
    'modifActivite' => [['id'], ['_controller' => 'App\\Controller\\ActiviteController::modifActivite'], [], [['variable', '', '[^/]++', 'id'], ['text', '/modifActivite']], [], []],
    'display_reglement' => [[], ['_controller' => 'App\\Controller\\ReglementController::index'], [], [['text', '/reglement']], [], []],
    'app_reglement' => [[], ['_controller' => 'App\\Controller\\ReglementController::addReglement'], [], [['text', '/addReglement']], [], []],
    'supp_reglement' => [['id'], ['_controller' => 'App\\Controller\\ReglementController::suppressionActivite'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/removeReglement']], [], []],
    'modifReglement' => [['id'], ['_controller' => 'App\\Controller\\ReglementController::modifReglement'], [], [['variable', '', '[^/]++', 'id'], ['text', '/modifRegelement']], [], []],
];
